"""
Dialect-neutral table definitions.

Each entry is (table_name, [(col_name, col_type_with_default), ...]).
Types are limited to TEXT and INTEGER for cross-DB portability.
"""

TABLES = [
    ("chatbots", [
        ("id", "TEXT PRIMARY KEY"),
        ("name", "TEXT NOT NULL DEFAULT ''"),
        ("description", "TEXT DEFAULT ''"),
        ("tag", "TEXT DEFAULT ''"),
        ("is_enabled", "INTEGER DEFAULT 1"),
        ("is_deleted", "INTEGER DEFAULT 0"),
        ("source_type", "TEXT DEFAULT 'filesystem'"),
        ("source_folder", "TEXT DEFAULT ''"),
        ("source_texts", "TEXT DEFAULT '[]'"),
        ("model", "TEXT DEFAULT ''"),
        ("created_at", "TEXT DEFAULT ''"),
        ("updated_at", "TEXT DEFAULT ''"),
    ]),
    ("chat_histories", [
        ("id", "TEXT PRIMARY KEY"),
        ("chatbot_id", "TEXT NOT NULL"),
        ("user_id", "TEXT DEFAULT 'default'"),
        ("title", "TEXT DEFAULT ''"),
        ("messages", "TEXT DEFAULT '[]'"),
        ("created_at", "TEXT DEFAULT ''"),
        ("updated_at", "TEXT DEFAULT ''"),
    ]),
    ("tools", [
        ("id", "TEXT PRIMARY KEY"),
        ("name", "TEXT NOT NULL DEFAULT ''"),
        ("type", "INTEGER DEFAULT 0"),
        ("tag", "TEXT DEFAULT ''"),
        ("sort_index", "INTEGER DEFAULT 0"),
        ("is_enabled", "INTEGER DEFAULT 1"),
        ("description", "TEXT DEFAULT ''"),
        ("prompt", "TEXT DEFAULT ''"),
        ("system_prompt", "TEXT DEFAULT ''"),
        ("model", "TEXT DEFAULT ''"),
        ("chatbot_id", "TEXT DEFAULT ''"),
        ("endpoint_url", "TEXT DEFAULT ''"),
        ("endpoint_method", "INTEGER DEFAULT 0"),
        ("endpoint_headers", "TEXT DEFAULT ''"),
        ("endpoint_body", "TEXT DEFAULT ''"),
        ("agent_functions", "TEXT DEFAULT '[]'"),
        ("pipeline_id", "TEXT DEFAULT ''"),
        ("request_inputs", "TEXT DEFAULT '[]'"),
        ("created_at", "TEXT DEFAULT ''"),
        ("updated_at", "TEXT DEFAULT ''"),
    ]),
    ("pipelines", [
        ("id", "TEXT PRIMARY KEY"),
        ("name", "TEXT NOT NULL DEFAULT ''"),
        ("description", "TEXT DEFAULT ''"),
        ("tag", "TEXT DEFAULT ''"),
        ("steps", "TEXT DEFAULT '[]'"),
        ("inputs", "TEXT DEFAULT '[]'"),
        ("edges", "TEXT DEFAULT '[]'"),
        ("guidance", "TEXT DEFAULT ''"),
        ("created_at", "TEXT DEFAULT ''"),
        ("updated_at", "TEXT DEFAULT ''"),
    ]),
    ("triggers", [
        ("id", "TEXT PRIMARY KEY"),
        ("name", "TEXT NOT NULL DEFAULT ''"),
        ("description", "TEXT DEFAULT ''"),
        ("tag", "TEXT DEFAULT ''"),
        ("is_enabled", "INTEGER DEFAULT 0"),
        ("trigger_type", "INTEGER DEFAULT 0"),
        ("cron_expression", "TEXT DEFAULT '0 * * * *'"),
        ("watch_path", "TEXT DEFAULT ''"),
        ("watch_patterns", "TEXT DEFAULT ''"),
        ("watch_events", "TEXT DEFAULT '[]'"),
        ("rss_url", "TEXT DEFAULT ''"),
        ("rss_poll_minutes", "INTEGER DEFAULT 60"),
        ("code", "TEXT DEFAULT ''"),
        ("pip_dependencies", "TEXT DEFAULT '[]'"),
        ("env_variables", "TEXT DEFAULT '[]'"),
        ("outputs", "TEXT DEFAULT '[]'"),
        ("connections", "TEXT DEFAULT '[]'"),
        ("last_fired_at", "TEXT DEFAULT ''"),
        ("last_status", "TEXT DEFAULT ''"),
        ("fire_count", "INTEGER DEFAULT 0"),
        ("created_at", "TEXT DEFAULT ''"),
        ("updated_at", "TEXT DEFAULT ''"),
    ]),
    ("pipeline_runs", [
        ("id", "TEXT PRIMARY KEY"),
        ("pipeline_id", "TEXT NOT NULL"),
        ("pipeline_snapshot", "TEXT DEFAULT '{}'"),
        ("steps", "TEXT DEFAULT '[]'"),
        ("inputs", "TEXT DEFAULT '[]'"),
        ("outputs", "TEXT DEFAULT '[]'"),
        ("status", "INTEGER DEFAULT 0"),
        ("current_step", "INTEGER DEFAULT 0"),
        ("guidance", "TEXT DEFAULT ''"),
        ("created_at", "TEXT DEFAULT ''"),
        ("completed_at", "TEXT DEFAULT ''"),
        ("updated_at", "TEXT DEFAULT ''"),
    ]),
    ("pipeline_memories", [
        ("id", "TEXT PRIMARY KEY"),
        ("pipeline_id", "TEXT NOT NULL"),
        ("memory_node_id", "TEXT NOT NULL"),
        ("name", "TEXT DEFAULT ''"),
        ("messages", "TEXT DEFAULT '[]'"),
        ("created_at", "TEXT DEFAULT ''"),
        ("updated_at", "TEXT DEFAULT ''"),
    ]),
    ("users", [
        ("id", "TEXT PRIMARY KEY"),
        ("username", "TEXT NOT NULL DEFAULT ''"),
        ("email", "TEXT DEFAULT ''"),
        ("password_hash", "TEXT DEFAULT ''"),
        ("role", "TEXT DEFAULT 'user'"),
        ("is_active", "INTEGER DEFAULT 1"),
        ("created_at", "TEXT DEFAULT ''"),
        ("updated_at", "TEXT DEFAULT ''"),
    ]),
    ("role_permissions", [
        ("id", "TEXT PRIMARY KEY"),
        ("resource_type", "TEXT NOT NULL DEFAULT ''"),
        ("can_create", "INTEGER DEFAULT 1"),
        ("can_edit", "INTEGER DEFAULT 1"),
        ("can_delete", "INTEGER DEFAULT 1"),
        ("can_use", "INTEGER DEFAULT 1"),
        ("created_at", "TEXT DEFAULT ''"),
        ("updated_at", "TEXT DEFAULT ''"),
    ]),
    ("user_permissions", [
        ("id", "TEXT PRIMARY KEY"),
        ("user_id", "TEXT NOT NULL DEFAULT ''"),
        ("resource_type", "TEXT NOT NULL DEFAULT ''"),
        ("can_create", "INTEGER DEFAULT 0"),
        ("can_edit", "INTEGER DEFAULT 0"),
        ("can_delete", "INTEGER DEFAULT 0"),
        ("created_at", "TEXT DEFAULT ''"),
        ("updated_at", "TEXT DEFAULT ''"),
    ]),
    ("user_resource_access", [
        ("id", "TEXT PRIMARY KEY"),
        ("user_id", "TEXT NOT NULL DEFAULT ''"),
        ("resource_type", "TEXT NOT NULL DEFAULT ''"),
        ("resource_id", "TEXT NOT NULL DEFAULT ''"),
        ("created_at", "TEXT DEFAULT ''"),
        ("updated_at", "TEXT DEFAULT ''"),
    ]),
    ("models", [
        ("id", "TEXT PRIMARY KEY"),
        ("model_id", "TEXT NOT NULL DEFAULT ''"),
        ("name", "TEXT NOT NULL DEFAULT ''"),
        ("provider", "TEXT NOT NULL DEFAULT 'anthropic'"),
        ("input_cost", "REAL DEFAULT 0"),
        ("output_cost", "REAL DEFAULT 0"),
        ("created_at", "TEXT DEFAULT ''"),
        ("updated_at", "TEXT DEFAULT ''"),
    ]),
    ("custom_variables", [
        ("id", "TEXT PRIMARY KEY"),
        ("resource_type", "TEXT NOT NULL"),
        ("resource_id", "TEXT NOT NULL"),
        ("name", "TEXT NOT NULL"),
        ("value", "TEXT DEFAULT ''"),
        ("created_at", "TEXT DEFAULT ''"),
        ("updated_at", "TEXT DEFAULT ''"),
    ]),
    ("task_plans", [
        ("id", "TEXT PRIMARY KEY"),
        ("name", "TEXT NOT NULL DEFAULT ''"),
        ("description", "TEXT DEFAULT ''"),
        ("tag", "TEXT DEFAULT ''"),
        ("sort_index", "INTEGER DEFAULT 0"),
        ("is_enabled", "INTEGER DEFAULT 1"),
        ("request", "TEXT DEFAULT ''"),
        ("inputs", "TEXT DEFAULT '[]'"),
        ("plan", "TEXT DEFAULT '[]'"),
        ("model", "TEXT DEFAULT ''"),
        ("created_at", "TEXT DEFAULT ''"),
        ("updated_at", "TEXT DEFAULT ''"),
    ]),
    ("task_runs", [
        ("id", "TEXT PRIMARY KEY"),
        ("task_plan_id", "TEXT DEFAULT ''"),
        ("request", "TEXT DEFAULT ''"),
        ("input_values", "TEXT DEFAULT '{}'"),
        ("plan", "TEXT DEFAULT '[]'"),
        ("status", "INTEGER DEFAULT 0"),
        ("output", "TEXT DEFAULT ''"),
        ("model", "TEXT DEFAULT ''"),
        ("total_cost", "TEXT DEFAULT '[]'"),
        ("created_at", "TEXT DEFAULT ''"),
        ("updated_at", "TEXT DEFAULT ''"),
    ]),
]

# Foreign keys: {child_table: [(child_col, parent_table, parent_col), ...]}
FOREIGN_KEYS = {
    "chat_histories": [("chatbot_id", "chatbots", "id")],
    "pipeline_runs": [("pipeline_id", "pipelines", "id")],
    "pipeline_memories": [("pipeline_id", "pipelines", "id")],
}

# Ordered migrations: (table, column, type_with_default)
MIGRATIONS = [
    ("pipeline_runs", "updated_at", "TEXT DEFAULT ''"),
    ("chatbots", "github_owner", "TEXT DEFAULT ''"),
    ("chatbots", "github_repo", "TEXT DEFAULT ''"),
    ("chatbots", "github_branch", "TEXT DEFAULT 'main'"),
    ("chatbots", "github_folder", "TEXT DEFAULT ''"),
    ("pipeline_runs", "rerun_from", "TEXT DEFAULT '{}'"),
    ("tools", "pip_dependencies", "TEXT DEFAULT '[]'"),
    ("tools", "env_variables", "TEXT DEFAULT '[]'"),
    ("tools", "mcp_servers", "TEXT DEFAULT '[]'"),
    ("pipeline_runs", "tool_id", "TEXT DEFAULT ''"),
    ("tools", "max_passes", "INTEGER DEFAULT 5"),
    ("chatbots", "sort_index", "INTEGER DEFAULT 0"),
    ("pipelines", "sort_index", "INTEGER DEFAULT 0"),
    ("triggers", "sort_index", "INTEGER DEFAULT 0"),
    ("pipelines", "memories", "TEXT DEFAULT '[]'"),
    ("pipeline_runs", "memories", "TEXT DEFAULT '[]'"),
    ("users", "oauth_provider", "TEXT DEFAULT ''"),
    ("users", "oauth_id", "TEXT DEFAULT ''"),
    ("pipeline_runs", "user_id", "TEXT DEFAULT 'default'"),
    ("users", "must_change_password", "INTEGER DEFAULT 0"),
    ("users", "display_name", "TEXT DEFAULT ''"),
    ("user_resource_access", "updated_at", "TEXT DEFAULT ''"),
    ("pipeline_runs", "log_entries", "TEXT DEFAULT '[]'"),
    ("tools", "endpoint_query", "TEXT DEFAULT '[]'"),
    ("tools", "response_structure", "TEXT DEFAULT '[]'"),
    ("tools", "endpoint_timeout", "INTEGER DEFAULT 60"),
    ("models", "sort_order", "INTEGER DEFAULT 0"),
    ("tools", "export_uid", "TEXT DEFAULT ''"),
    ("tools", "export_version", "INTEGER DEFAULT 0"),
    ("pipelines", "export_uid", "TEXT DEFAULT ''"),
    ("pipelines", "export_version", "INTEGER DEFAULT 0"),
    ("triggers", "export_uid", "TEXT DEFAULT ''"),
    ("triggers", "export_version", "INTEGER DEFAULT 0"),
    ("tools", "image_url", "TEXT DEFAULT ''"),
    ("pipelines", "image_url", "TEXT DEFAULT ''"),
    ("triggers", "image_url", "TEXT DEFAULT ''"),
    ("task_plans", "auto_run", "INTEGER DEFAULT 1"),
    ("pipelines", "validation_model", "TEXT DEFAULT ''"),
]
