"""
Google Gemini LLM provider implementation.

Translates between Anthropic-format messages (used by all consumers)
and Google Gemini API format, so no changes are needed to agent_service,
pipeline_engine, chatbot_routes, or tool_routes.
"""

import asyncio
import json
import logging
import uuid
from typing import AsyncGenerator

from google import genai
from google.genai import types

from config import DEFAULT_MODEL
from event_bus import broadcast
from services.llm_provider import LLMProvider

logger = logging.getLogger(__name__)

MAX_RETRIES = 3

EVALUATE_CONDITION_TOOL_GEMINI = types.FunctionDeclaration(
    name="evaluate_condition",
    description="Return the boolean result of evaluating a condition.",
    parameters={
        "type": "object",
        "properties": {
            "result": {
                "type": "boolean",
                "description": "true if the condition is met, false otherwise",
            },
            "reasoning": {
                "type": "string",
                "description": "Brief explanation of why the condition is true or false",
            },
        },
        "required": ["result", "reasoning"],
    },
)


# ── Translation helpers ──────────────────────────────────────────────


def _generate_tool_id() -> str:
    """Generate a synthetic tool_use ID in Anthropic format."""
    return "toolu_" + uuid.uuid4().hex[:24]


def _anthropic_messages_to_gemini(messages: list[dict]) -> list[types.Content]:
    """Convert Anthropic-format messages to Gemini Content objects."""
    contents: list[types.Content] = []

    for msg in messages:
        role = msg.get("role", "user")
        gemini_role = "model" if role == "assistant" else "user"
        content = msg.get("content")
        parts: list[types.Part] = []

        if isinstance(content, str):
            parts.append(types.Part.from_text(text=content))
        elif isinstance(content, list):
            for block in content:
                if not isinstance(block, dict):
                    continue
                btype = block.get("type")

                if btype == "text":
                    text = block.get("text", "")
                    if text:
                        parts.append(types.Part.from_text(text=text))

                elif btype == "tool_use":
                    parts.append(types.Part.from_function_call(
                        name=block["name"],
                        args=block.get("input", {}),
                    ))

                elif btype == "tool_result":
                    tool_content = block.get("content", "")
                    if isinstance(tool_content, list):
                        text_parts = []
                        for sub in tool_content:
                            if isinstance(sub, dict) and sub.get("type") == "text":
                                text_parts.append(sub.get("text", ""))
                        tool_content = "\n".join(text_parts)
                    # Gemini correlates by function name, not by ID.
                    # We need to find the function name from the tool_use_id.
                    # Look back through previous contents to find the matching call.
                    func_name = _find_function_name_by_id(
                        contents, block.get("tool_use_id", "")
                    )
                    if func_name:
                        parts.append(types.Part.from_function_response(
                            name=func_name,
                            response={"result": str(tool_content)},
                        ))
        else:
            parts.append(types.Part.from_text(text=str(content) if content else ""))

        if parts:
            contents.append(types.Content(role=gemini_role, parts=parts))

    return contents


def _find_function_name_by_id(contents: list[types.Content], tool_use_id: str) -> str:
    """Search previous contents for a function call matching the given tool_use_id.

    Since Gemini doesn't have IDs, we store the ID->name mapping in a side channel.
    But for the translation layer, we track generated IDs in the response.
    For messages coming from the conversation history, we match by position/name.
    """
    if not tool_use_id:
        return ""
    # The tool_use_id was generated by us in _gemini_response_to_anthropic_content.
    # In practice, the messages list has the original Anthropic-format tool_use blocks
    # with the ID. We need to search the *original* messages for the name.
    # Since we only have the already-converted contents here, fall back to
    # returning the last function call name from model messages.
    for c in reversed(contents):
        if c.role == "model":
            for part in c.parts:
                if hasattr(part, "function_call") and part.function_call:
                    return part.function_call.name
    return ""


def _anthropic_messages_to_gemini_with_name_lookup(
    messages: list[dict],
) -> list[types.Content]:
    """Convert messages, building a tool_use_id -> name map from the source messages."""
    # First pass: build ID -> name map from the original Anthropic messages
    id_to_name: dict[str, str] = {}
    for msg in messages:
        content = msg.get("content")
        if isinstance(content, list):
            for block in content:
                if isinstance(block, dict) and block.get("type") == "tool_use":
                    id_to_name[block.get("id", "")] = block["name"]

    # Second pass: convert messages
    contents: list[types.Content] = []

    for msg in messages:
        role = msg.get("role", "user")
        gemini_role = "model" if role == "assistant" else "user"
        content = msg.get("content")
        parts: list[types.Part] = []

        if isinstance(content, str):
            parts.append(types.Part.from_text(text=content))
        elif isinstance(content, list):
            for block in content:
                if not isinstance(block, dict):
                    continue
                btype = block.get("type")

                if btype == "text":
                    text = block.get("text", "")
                    if text:
                        parts.append(types.Part.from_text(text=text))

                elif btype == "tool_use":
                    parts.append(types.Part.from_function_call(
                        name=block["name"],
                        args=block.get("input", {}),
                    ))

                elif btype == "tool_result":
                    tool_content = block.get("content", "")
                    if isinstance(tool_content, list):
                        text_parts = []
                        for sub in tool_content:
                            if isinstance(sub, dict) and sub.get("type") == "text":
                                text_parts.append(sub.get("text", ""))
                        tool_content = "\n".join(text_parts)
                    func_name = id_to_name.get(block.get("tool_use_id", ""), "")
                    if func_name:
                        parts.append(types.Part.from_function_response(
                            name=func_name,
                            response={"result": str(tool_content)},
                        ))
        else:
            parts.append(types.Part.from_text(text=str(content) if content else ""))

        if parts:
            contents.append(types.Content(role=gemini_role, parts=parts))

    return contents


def _anthropic_tools_to_gemini(tools: list[dict]) -> list[types.Tool]:
    """Convert Anthropic tool definitions to Gemini Tool format."""
    declarations = []
    for tool in tools:
        declarations.append(types.FunctionDeclaration(
            name=tool["name"],
            description=tool.get("description", ""),
            parameters=tool.get("input_schema", {}),
        ))
    return [types.Tool(function_declarations=declarations)]


def _gemini_response_to_anthropic_content(response) -> list[dict]:
    """Convert a Gemini response to Anthropic-format content blocks."""
    blocks: list[dict] = []

    if not response.candidates:
        return [{"type": "text", "text": ""}]

    candidate = response.candidates[0]
    if not candidate.content or not candidate.content.parts:
        return [{"type": "text", "text": ""}]

    for part in candidate.content.parts:
        if part.text is not None:
            blocks.append({"type": "text", "text": part.text})
        elif part.function_call:
            args = dict(part.function_call.args) if part.function_call.args else {}
            blocks.append({
                "type": "tool_use",
                "id": _generate_tool_id(),
                "name": part.function_call.name,
                "input": args,
            })

    if not blocks:
        blocks.append({"type": "text", "text": ""})

    return blocks


def _gemini_finish_reason_to_anthropic(response) -> str:
    """Map Gemini finish reason to Anthropic stop_reason."""
    if not response.candidates:
        return "end_turn"

    candidate = response.candidates[0]

    # Check if response contains function calls
    if candidate.content and candidate.content.parts:
        for part in candidate.content.parts:
            if part.function_call:
                return "tool_use"

    finish = candidate.finish_reason
    if finish == "MAX_TOKENS":
        return "max_tokens"
    return "end_turn"


def _extract_usage(response) -> dict:
    """Extract token usage from a Gemini response."""
    meta = response.usage_metadata if response.usage_metadata else None
    return {
        "input_tokens": meta.prompt_token_count if meta and meta.prompt_token_count else 0,
        "output_tokens": meta.candidates_token_count if meta and meta.candidates_token_count else 0,
    }


def _map_tool_choice(tool_choice: dict | None) -> types.ToolConfig | None:
    """Convert Anthropic tool_choice format to Gemini ToolConfig."""
    if not tool_choice:
        return None

    choice_type = tool_choice.get("type", "auto")

    if choice_type == "auto":
        return types.ToolConfig(
            function_calling_config=types.FunctionCallingConfig(mode="AUTO")
        )
    elif choice_type == "any":
        return types.ToolConfig(
            function_calling_config=types.FunctionCallingConfig(mode="ANY")
        )
    elif choice_type == "tool" and "name" in tool_choice:
        return types.ToolConfig(
            function_calling_config=types.FunctionCallingConfig(
                mode="ANY",
                allowed_function_names=[tool_choice["name"]],
            )
        )

    return None


class GeminiProvider(LLMProvider):
    """Google Gemini provider that translates Anthropic-format messages to/from Gemini API."""

    def __init__(self, api_key: str):
        self.client = genai.Client(api_key=api_key)
        logger.info("[Gemini] Provider initialized")

    async def _retry_on_rate_limit(self, api_call, context: str = ""):
        """Retry an async API call on rate limit errors up to MAX_RETRIES times."""
        for attempt in range(MAX_RETRIES):
            try:
                return await api_call()
            except Exception as e:
                # google-genai raises various exceptions for rate limits
                error_str = str(e).lower()
                is_rate_limit = (
                    "429" in error_str
                    or "resource exhausted" in error_str
                    or "rate limit" in error_str
                )
                if not is_rate_limit or attempt == MAX_RETRIES - 1:
                    raise
                retry_after = 30
                logger.warning(
                    "Rate limited (attempt %d/%d) on %s — retrying in %ds",
                    attempt + 1, MAX_RETRIES, context, retry_after,
                )
                broadcast("rate_limit", {
                    "retry_after": retry_after,
                    "attempt": attempt + 1,
                    "max_retries": MAX_RETRIES,
                    "context": context,
                })
                await asyncio.sleep(retry_after)

    # ── LLMProvider interface ────────────────────────────────────────

    async def stream_chat(
        self,
        messages: list[dict],
        model: str = "",
        system_prompt: str = "",
    ) -> AsyncGenerator[dict, None]:
        model = model or DEFAULT_MODEL
        contents = _anthropic_messages_to_gemini_with_name_lookup(messages)

        logger.info("[Gemini] stream_chat called — model=%s, %d contents", model, len(contents))

        config = types.GenerateContentConfig()
        if system_prompt:
            config.system_instruction = system_prompt

        for attempt in range(MAX_RETRIES):
            try:
                response_stream = self.client.aio.models.generate_content_stream(
                    model=model,
                    contents=contents,
                    config=config,
                )
                usage_data = {}
                async for chunk in response_stream:
                    if chunk.text:
                        yield {"type": "text", "text": chunk.text}
                    if chunk.usage_metadata:
                        usage_data = {
                            "input_tokens": chunk.usage_metadata.prompt_token_count or 0,
                            "output_tokens": chunk.usage_metadata.candidates_token_count or 0,
                        }
                yield {
                    "type": "usage",
                    "model": model,
                    "input_tokens": usage_data.get("input_tokens", 0),
                    "output_tokens": usage_data.get("output_tokens", 0),
                }
                logger.info("[Gemini] stream_chat completed successfully")
                return  # success
            except Exception as e:
                error_str = str(e).lower()
                is_rate_limit = (
                    "429" in error_str
                    or "resource exhausted" in error_str
                    or "rate limit" in error_str
                )
                if not is_rate_limit or attempt == MAX_RETRIES - 1:
                    raise
                retry_after = 30
                logger.warning(
                    "Rate limited (attempt %d/%d) on stream_chat — retrying in %ds",
                    attempt + 1, MAX_RETRIES, retry_after,
                )
                broadcast("rate_limit", {
                    "retry_after": retry_after,
                    "attempt": attempt + 1,
                    "max_retries": MAX_RETRIES,
                    "context": "stream_chat",
                })
                await asyncio.sleep(retry_after)

    async def complete_chat(
        self,
        messages: list[dict],
        model: str = "",
        system_prompt: str = "",
    ) -> tuple[str, dict]:
        model = model or DEFAULT_MODEL
        contents = _anthropic_messages_to_gemini_with_name_lookup(messages)

        logger.info("[Gemini] complete_chat called — model=%s, %d contents", model, len(contents))

        config = types.GenerateContentConfig()
        if system_prompt:
            config.system_instruction = system_prompt

        response = await self._retry_on_rate_limit(
            lambda: self.client.aio.models.generate_content(
                model=model,
                contents=contents,
                config=config,
            ),
            "complete_chat",
        )

        text = response.text or ""
        usage = {"model": model, **_extract_usage(response)}
        logger.info("[Gemini] complete_chat done — %d chars, %d in / %d out tokens",
                     len(text), usage["input_tokens"], usage["output_tokens"])
        return text, usage

    async def call_with_tools(
        self,
        messages: list[dict],
        tools: list[dict],
        model: str = "",
        system_prompt: str = "",
        tool_choice: dict = None,
        max_tokens: int = 16384,
    ) -> dict:
        model = model or DEFAULT_MODEL
        contents = _anthropic_messages_to_gemini_with_name_lookup(messages)
        gemini_tools = _anthropic_tools_to_gemini(tools)

        logger.info("[Gemini] call_with_tools — model=%s, %d contents, %d tools",
                     model, len(contents), len(tools))

        config = types.GenerateContentConfig(
            tools=gemini_tools,
            max_output_tokens=max_tokens,
        )
        if system_prompt:
            config.system_instruction = system_prompt

        tool_config = _map_tool_choice(tool_choice)
        if tool_config:
            config.tool_config = tool_config

        response = await self._retry_on_rate_limit(
            lambda: self.client.aio.models.generate_content(
                model=model,
                contents=contents,
                config=config,
            ),
            "call_with_tools",
        )

        content_blocks = _gemini_response_to_anthropic_content(response)
        stop_reason = _gemini_finish_reason_to_anthropic(response)
        usage = {"model": model, **_extract_usage(response)}

        tool_names = [b["name"] for b in content_blocks if b.get("type") == "tool_use"]
        logger.info("[Gemini] call_with_tools done — stop_reason=%s, tool_calls=%s, %d in / %d out tokens",
                     stop_reason, tool_names or "none",
                     usage["input_tokens"], usage["output_tokens"])

        return {
            "content": content_blocks,
            "stop_reason": stop_reason,
            "usage": usage,
        }

    # stream_with_tools: uses base class fallback (call_with_tools + synthetic events)

    async def evaluate_condition(
        self,
        messages: list[dict],
        model: str = "",
        system_prompt: str = "",
    ) -> tuple[bool, str, dict]:
        model = model or DEFAULT_MODEL
        contents = _anthropic_messages_to_gemini_with_name_lookup(messages)

        config = types.GenerateContentConfig(
            tools=[types.Tool(function_declarations=[EVALUATE_CONDITION_TOOL_GEMINI])],
            tool_config=types.ToolConfig(
                function_calling_config=types.FunctionCallingConfig(
                    mode="ANY",
                    allowed_function_names=["evaluate_condition"],
                )
            ),
            max_output_tokens=256,
        )
        if system_prompt:
            config.system_instruction = system_prompt

        response = await self._retry_on_rate_limit(
            lambda: self.client.aio.models.generate_content(
                model=model,
                contents=contents,
                config=config,
            ),
            "evaluate_condition",
        )

        result = False
        reasoning = ""

        if response.candidates and response.candidates[0].content:
            for part in response.candidates[0].content.parts:
                if part.function_call and part.function_call.name == "evaluate_condition":
                    args = dict(part.function_call.args) if part.function_call.args else {}
                    result = bool(args.get("result", False))
                    reasoning = args.get("reasoning", "")
                    break

        usage = {"model": model, **_extract_usage(response)}
        return result, reasoning, usage
