<script setup lang="ts">
import { ref, computed, watch } from 'vue'
import { useRoute } from 'vue-router'
import { marked } from 'marked'

const route = useRoute()
const activeTab = ref<'tos' | 'license'>((route.query.tab as 'tos' | 'license') || 'tos')

watch(() => route.query.tab, (tab) => {
  if (tab === 'tos' || tab === 'license') activeTab.value = tab
})

const tosMarkdown = `# Terms of Service

**Effective Date:** January 1, 2025
**Last Updated:** March 24, 2025

By accessing, downloading, installing, or using CLAIRE ("the Software"), you agree to be bound by these Terms of Service ("Terms"). If you do not agree to these Terms, do not use the Software.

## 1. Acceptance of Terms

Your use of the Software constitutes your acceptance of and agreement to comply with these Terms. The licensor reserves the right to update these Terms at any time. Continued use of the Software after changes are posted constitutes acceptance of the revised Terms.

## 2. License

The Software is licensed under the PolyForm Noncommercial License 1.0.0. Use of the Software is subject to the terms and conditions of that license. Commercial use of the Software is expressly prohibited unless separate written permission is obtained from the licensor.

## 3. Disclaimer of Warranties

THE SOFTWARE IS PROVIDED "AS IS" AND "AS AVAILABLE," WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE, AND NON-INFRINGEMENT. THE LICENSOR MAKES NO WARRANTY THAT THE SOFTWARE WILL MEET YOUR REQUIREMENTS, OPERATE WITHOUT INTERRUPTION, BE SECURE, OR BE FREE OF ERRORS, BUGS, OR DEFECTS.

NO ADVICE OR INFORMATION, WHETHER ORAL OR WRITTEN, OBTAINED FROM THE LICENSOR OR THROUGH THE SOFTWARE SHALL CREATE ANY WARRANTY NOT EXPRESSLY STATED IN THESE TERMS.

## 4. Limitation of Liability

TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, IN NO EVENT SHALL THE LICENSOR, ITS CONTRIBUTORS, OR ANY AFFILIATED PARTIES BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, EXEMPLARY, OR PUNITIVE DAMAGES, INCLUDING BUT NOT LIMITED TO:

- Loss of profits, revenue, data, or business opportunities
- Loss of goodwill or reputation
- Cost of procurement of substitute goods or services
- Business interruption or downtime
- Any damages arising from unauthorized access to or alteration of your data or transmissions
- Any other pecuniary loss

THIS LIMITATION APPLIES WHETHER THE CLAIM IS BASED ON WARRANTY, CONTRACT, TORT (INCLUDING NEGLIGENCE), STRICT LIABILITY, OR ANY OTHER LEGAL THEORY, EVEN IF THE LICENSOR HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES.

IN NO EVENT SHALL THE LICENSOR'S TOTAL AGGREGATE LIABILITY EXCEED THE AMOUNT YOU PAID FOR THE SOFTWARE, IF ANY (WHICH, FOR OPEN-SOURCE DISTRIBUTION, IS ZERO).

## 5. Assumption of Risk

You acknowledge and agree that:

- You use the Software entirely at your own risk
- You are solely responsible for any damage to your computer systems, networks, data, or any other loss that results from your use of the Software
- You are solely responsible for evaluating the suitability and safety of the Software for your intended use
- The Software may interact with third-party services, APIs, and AI models whose behavior, availability, and output are outside the licensor's control

## 6. Indemnification

You agree to indemnify, defend, and hold harmless the licensor, its contributors, and any affiliated parties from and against any and all claims, damages, losses, liabilities, costs, and expenses (including reasonable attorneys' fees) arising out of or in connection with:

- Your use or misuse of the Software
- Your violation of these Terms
- Your violation of any applicable law or regulation
- Any content, data, or output generated through your use of the Software
- Any harm caused to third parties resulting from your use of the Software

## 7. User Responsibilities and Acceptable Use

You agree that you will NOT use the Software to:

- Violate any applicable local, state, national, or international law or regulation
- Generate, distribute, or facilitate content that is unlawful, harmful, threatening, abusive, harassing, defamatory, or otherwise objectionable
- Infringe upon or violate the intellectual property rights, privacy rights, or other rights of any third party
- Transmit malware, viruses, or any other malicious code
- Attempt to gain unauthorized access to any systems, networks, or data
- Engage in any activity that could damage, disable, overburden, or impair any server, network, or system
- Use the Software in any manner that could cause harm to individuals or organizations

You are solely responsible for all activity conducted through your use of the Software and for all content and output generated by or through the Software under your control.

## 8. AI-Generated Content

The Software may facilitate interactions with AI models and generate AI-assisted content. You acknowledge that:

- AI-generated output may be inaccurate, incomplete, biased, or otherwise unreliable
- You are solely responsible for reviewing, validating, and verifying any AI-generated content before relying on or distributing it
- The licensor makes no representations or warranties regarding the accuracy, reliability, or fitness of any AI-generated output
- You assume full responsibility for any decisions or actions taken based on AI-generated content

## 9. Third-Party Services

The Software may integrate with or rely on third-party services, APIs, and platforms. The licensor:

- Is not responsible for the availability, performance, or policies of any third-party service
- Does not warrant that third-party integrations will function without interruption or error
- Is not liable for any costs, fees, or charges incurred through your use of third-party services via the Software
- Is not responsible for how third-party services handle your data

Your use of third-party services is subject to those services' own terms and conditions.

## 10. Data and Privacy

The Software operates locally and does not collect or transmit personal data to the licensor. However:

- You are responsible for the security and handling of any data you process through the Software
- You are responsible for compliance with applicable data protection laws and regulations in your jurisdiction
- The licensor is not responsible for any data breaches, data loss, or unauthorized access that occurs through your use of the Software

## 11. No Professional Advice

Nothing provided by the Software constitutes professional, legal, financial, medical, or any other form of advice. The Software is a tool, and its output should not be relied upon as a substitute for professional judgment or consultation.

## 12. Termination

The licensor reserves the right to modify, suspend, or discontinue the Software at any time without notice or liability. Your rights under these Terms terminate automatically if you fail to comply with any provision. Upon termination, you must cease all use of the Software and destroy any copies in your possession.

## 13. Severability

If any provision of these Terms is found to be unenforceable or invalid, that provision shall be limited or eliminated to the minimum extent necessary so that these Terms shall otherwise remain in full force and effect.

## 14. Entire Agreement

These Terms, together with the PolyForm Noncommercial License 1.0.0, constitute the entire agreement between you and the licensor regarding the Software and supersede all prior agreements and understandings.

## 15. Governing Law

These Terms shall be governed by and construed in accordance with applicable law, without regard to conflict of law principles.

## 16. Contact

For questions about these Terms or to request commercial licensing, please contact the licensor through the project's official repository.`

const licenseMarkdown = `# PolyForm Noncommercial License 1.0.0

<https://polyformproject.org/licenses/noncommercial/1.0.0>

## Acceptance

In order to get any license under these terms, you must agree to them as both strict obligations and conditions to all your licenses.

## Copyright License

The licensor grants you a copyright license for the software to do everything you might do with the software that would otherwise infringe the licensor's copyright in it for any permitted purpose. However, you may only distribute the software according to Distribution License and make changes or new works based on the software according to Changes and New Works License.

## Distribution License

The licensor grants you an additional copyright license to distribute copies of the software. Your license to distribute covers distributing the software with changes and new works permitted by Changes and New Works License.

## Notices

You must ensure that anyone who gets a copy of any part of the software from you also gets a copy of these terms or the URL for them above, as well as copies of any plain-text lines beginning with \\\`Required Notice:\\\` that the licensor provided with the software. For example:

> Required Notice: Copyright Quentin McCain (2025-2026)

## Changes and New Works License

The licensor grants you an additional copyright license to make changes and new works based on the software for any permitted purpose.

## Patent License

The licensor grants you a patent license for the software that covers patent claims the licensor can license, or becomes able to license, that you would infringe by using the software.

## Noncommercial Purposes

Any noncommercial purpose is a permitted purpose.

## Personal Uses

Personal use for research, experiment, and testing for the benefit of public knowledge, personal study, private entertainment, hobby projects, amateur pursuits, or religious observance, without any anticipated commercial application, is use for a permitted purpose.

## Noncommercial Organizations

Use by any charitable organization, educational institution, public research organization, public safety or health organization, environmental protection organization, or government institution is use for a permitted purpose regardless of the source of funding or obligations resulting from the funding.

## Fair Use

You may have "fair use" rights for the software under the law. These terms do not limit them.

## No Other Rights

These terms do not allow you to sublicense or transfer any of your licenses to anyone else, or prevent the licensor from granting licenses to anyone else. These terms do not imply any other licenses.

## Patent Defense

If you make any written claim that the software infringes or contributes to infringement of any patent, your patent license for the software granted under these terms ends immediately. If your company makes such a claim, your patent license ends immediately for work on behalf of your company.

## Violations

The first time you are notified in writing that you have violated any of these terms, or done anything with the software not covered by your licenses, your licenses can nonetheless continue if you come into full compliance with these terms, and take practical steps to correct past violations, within 32 days of receiving notice. Otherwise, all your licenses end immediately.

## No Liability

***As far as the law allows, the software comes as is, without any warranty or condition, and the licensor will not be liable to you for any damages arising out of these terms or the use or nature of the software, under any kind of legal claim.***

## Definitions

The **licensor** is the individual or entity offering these terms, and the **software** is the software the licensor makes available under these terms.

**You** refers to the individual or entity agreeing to these terms.

**Your company** is any legal entity, sole proprietorship, or other kind of organization that you work for, plus all organizations that have control over, are under the control of, or are under common control with that organization. **Control** means ownership of substantially all the assets of an entity, or the power to direct its management and policies by vote, contract, or otherwise. Control can be direct or indirect.

**Your licenses** are all the licenses granted to you for the software under these terms.

**Use** means anything you do with the software requiring one of your licenses.`

const renderedTos = computed(() => marked(tosMarkdown))
const renderedLicense = computed(() => marked(licenseMarkdown))
</script>

<template>
  <div class="max-w-4xl mx-auto px-8 py-10">
    <!-- Header -->
    <div class="mb-8">
      <h1 class="text-2xl font-bold text-gray-100 mb-2">Legal</h1>
      <p class="text-sm text-gray-500">Terms of Service and License for Claire</p>
    </div>

    <!-- Tabs -->
    <div class="flex gap-1 mb-8 border-b border-gray-800">
      <button
        @click="activeTab = 'tos'"
        class="px-4 py-2.5 text-sm font-medium transition-colors border-b-2 -mb-px"
        :class="activeTab === 'tos'
          ? 'border-blue-500 text-blue-400'
          : 'border-transparent text-gray-500 hover:text-gray-300'"
      >
        Terms of Service
      </button>
      <button
        @click="activeTab = 'license'"
        class="px-4 py-2.5 text-sm font-medium transition-colors border-b-2 -mb-px"
        :class="activeTab === 'license'
          ? 'border-blue-500 text-blue-400'
          : 'border-transparent text-gray-500 hover:text-gray-300'"
      >
        License
      </button>
    </div>

    <!-- Content -->
    <article class="legal-content" v-if="activeTab === 'tos'" v-html="renderedTos" />
    <article class="legal-content" v-else v-html="renderedLicense" />
  </div>
</template>

<style scoped>
.legal-content :deep(h1) {
  font-size: 1.5rem;
  font-weight: 700;
  color: var(--color-gray-100);
  margin-bottom: 1rem;
}
.legal-content :deep(h2) {
  font-size: 1.125rem;
  font-weight: 600;
  color: var(--color-gray-200);
  margin-top: 2rem;
  margin-bottom: 0.75rem;
  padding-bottom: 0.5rem;
  border-bottom: 1px solid var(--color-gray-800);
}
.legal-content :deep(p) {
  color: var(--color-gray-400);
  line-height: 1.7;
  margin-bottom: 1rem;
  font-size: 0.875rem;
}
.legal-content :deep(ul) {
  list-style-type: disc;
  padding-left: 1.5rem;
  margin-bottom: 1rem;
}
.legal-content :deep(li) {
  color: var(--color-gray-400);
  font-size: 0.875rem;
  line-height: 1.7;
  margin-bottom: 0.25rem;
}
.legal-content :deep(strong) {
  color: var(--color-gray-300);
  font-weight: 600;
}
.legal-content :deep(em) {
  color: var(--color-gray-300);
}
.legal-content :deep(blockquote) {
  border-left: 3px solid var(--color-gray-700);
  padding-left: 1rem;
  margin: 1rem 0;
  color: var(--color-gray-500);
  font-style: italic;
}
.legal-content :deep(a) {
  color: #60a5fa;
  text-decoration: underline;
  text-underline-offset: 2px;
}
.legal-content :deep(a:hover) {
  color: #93bbfd;
}
.legal-content :deep(code) {
  background: var(--color-gray-900);
  padding: 0.125rem 0.375rem;
  border-radius: 0.25rem;
  font-size: 0.8125rem;
  color: var(--color-gray-300);
}
</style>
